label: 'GA4GH Genome Beacons'
tagline: 'A Driver Project of the Global Alliance for Genomics and Health GA4GH
and supported through ELIXIR'
description: |
  Beacon is an open standard for genomics data discovery, developed by members
  of the Global Alliance for Genomics & Health
keywords: genomics, cloud, Beacon, DNA, sharing, ELIXIR, GA4GH
site_domain_name: beacon-project.io
url: 'https://beacon-project.io'
baseurl: ""
site_parent_link: 'https://www.elixir-europe.org/about-us/implementation-studies/beacons'
github_organisation: ga4gh-beacon
show_downloads: true
future: true

# instructions for processing specific directories

include:
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

collections_dir: pages
collections:
  doc:
    output: true
    permalink: /doc/:path/
  people:
    output: true
    permalink: /people/:path/
  schemas:
    output: true
    permalink: /schemas/:path/
  minutes:
    output: true
    permalink: /minutes/:path/

# navigation blocks can be used to separate different categories and add e.g.
# external link block(s), in combination with a properly modified layout

nav_cat_blocks:
  General: 'General,categories,hide'
  follow_beacon: 'Beacon project,follow_beacon,show'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

General:
#  news: 'News'
  role: 'Beacon explained'
#  specification: 'Specification & Roadmap'
#  network: 'Beacon Networks'
#  events: 'News and Events'
  howto: 'Examples, Guides & FAQ'
#  people: 'Contributors & Teams'
#  contact: Contacts
#  minutes: Beacon working groups
  
follow_beacon:
#  news: 'News'
#  role: 'Beacon explained'
  specification: 'Specification & Roadmap'
#  network: 'Beacon Networks'
  events: 'News and Events'
#  howto: 'Examples, Guides & FAQ'
  people: 'Contributors & Teams'
#  contact: Contacts
  minutes: Beacon working groups

categories-date-sorted:
  - news
  - events

tags-date-sorted:
  - releases
  - press
  - versions
  - events

related_sites:
  'ELIXIR BeaconNetwork': 'https://beacon-network.elixir-europe.org'
  'Beacon @ ELIXIR': 'http://www.elixir-europe.org/about-us/implementation-studies/beacons'
  GA4GH: 'http://ga4gh.org'
  'beacon-network.org': 'http://beacon-network.org'
  'Beacon<span style="color: red; font-weight: 800;">+</span>': 'http://beacon.progenetix.org/ui/'
  'GA4GH::SchemaBlocks': 'http://schemablocks.org'
  'GA4GH::Discovery': 'http://ga4gh-discovery.github.io'

github_projects:
  'Beacon API and Tools': 'http://github.com/ga4gh-beacon/'
  'SchemaBlocks': 'http://github.com/ga4gh-schemablocks/'

# tag_cloud items

cloud_tags:
  - admin
#  - beacon
  - clinical
  - code
#  - compliance
  - contacts
#  - CNV
#  - developers
  - development
#  - EB
  - events
  - filters
  - FAQ
  - minutes
  - network
  - press
#  - proposal
#  - queries
  - releases
#  - roadmap
  - specification
  - schemas
#  - SV
#  - teams
  - v2
#  - VCF
#  - versions
#  - website

# additional Jekyll instructions

plugins:
 - jekyll-seo-tag
type: website
navigation_max_items: 4     # number of shown links in current category
emptyArray: []              # dummy element for array initialisation
